# Generated by Django 4.2.3 on 2023-08-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_rating_alter_sale_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='seller',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Слаг'),
        ),
    ]
