# Generated by Django 4.2.3 on 2023-08-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=53, null=True, verbose_name='Описание'),
        ),
    ]
