# Generated by Django 4.2.3 on 2023-10-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_saled',
            field=models.BigIntegerField(default=0, verbose_name='Количество купленных товаров'),
        ),
    ]
