# Generated by Django 4.2.3 on 2023-10-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_amount_saled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount_saled',
            new_name='amount_sold',
        ),
    ]
