# Generated by Django 4.2.3 on 2023-11-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_phone_number_and_more'),
        ('products', '0011_alter_product_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feedback_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('main_content', models.TextField(verbose_name='Основная часть')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='accounts.userprofile', verbose_name='Автор')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='products.product', verbose_name='Продукты')),
            ],
        ),
    ]
