# Generated by Django 4.2.3 on 2023-11-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_brand_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='preview',
            field=models.ImageField(default='path_to_static/no_image_default.jpg', upload_to='path_to_media', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='preview',
            field=models.ImageField(default='path_to_static/no_image_default.jpg', upload_to='path_to_media', verbose_name='Превью'),
        ),
    ]
