# Generated by Django 4.2.3 on 2023-11-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='path_to_static/no_image_available.jpg', null=True, upload_to='avatars', verbose_name='Фото'),
        ),
    ]
